apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-metricas
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: telegraf
          image: telegraf:1.18
          resources:
            limits:
              memory: "128Mi"
            requests:
              cpu: "250m"