apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: rc-nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.4
          ports:
            - containerPort: 80
