apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    name: myapp2
spec:
  containers:
  - name: myapp2
    image: nginx:1.21.4
    env:
      - name: USUARIO_SECRETO
        valueFrom:
          secretKeyRef:
            name: misecreto
            key: user.txt
      - name: PASSWORD_SECRETO
        valueFrom:
          secretKeyRef:
            name: misecreto
            key: password.txt
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80

# Crear secreto
# kubectl create secret generic misecreto --from-file=user.txt --from-file=password.txt