apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:1.21.4
    volumeMounts:
      - name: secreto
        mountPath: "/etc/secreto"
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  volumes:
    - name: secreto
      secret:
        secretName: misecreto 