apiVersion: v1
kind: Pod
metadata:
  name: emptypod
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21.4
    volumeMounts:
      - mountPath: /datos
        name: volumen-datos
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  volumes:
    - name: volumen-datos
      hostPath:
        path: /nodo/datos
        type: DirectoryOrCreate